{
  "formatVersion": "1.1",
  "component": {
    "group": "ru.litvishchenkoaa",
    "module": "logging-starter-gradle",
    "version": "1.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "logging-starter-gradle-1.1-SNAPSHOT.jar",
          "url": "logging-starter-gradle-1.1-SNAPSHOT.jar",
          "size": 1229,
          "sha512": "e57f57e19cd253a3a2676841e31ed7c8b3b27a25e36de50dbadaf9305db2424918ce4748963f5a52cf6f5671e9091e829fa2a4730023b9b286d9edefaaf2ba40",
          "sha256": "486da113e5d051389469bee2ecafc510e4899ff4ee97c433ad1eb40116c5818e",
          "sha1": "0f99dd97d61fc8014ae858b09521200fabf3e865",
          "md5": "b1bb9296cdfe5b91e5976a22ad5ec660"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logging-starter-gradle-1.1-SNAPSHOT.jar",
          "url": "logging-starter-gradle-1.1-SNAPSHOT.jar",
          "size": 1229,
          "sha512": "e57f57e19cd253a3a2676841e31ed7c8b3b27a25e36de50dbadaf9305db2424918ce4748963f5a52cf6f5671e9091e829fa2a4730023b9b286d9edefaaf2ba40",
          "sha256": "486da113e5d051389469bee2ecafc510e4899ff4ee97c433ad1eb40116c5818e",
          "sha1": "0f99dd97d61fc8014ae858b09521200fabf3e865",
          "md5": "b1bb9296cdfe5b91e5976a22ad5ec660"
        }
      ]
    }
  ]
}
